// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spotify.Infrastructure.Persistance.Context;

#nullable disable

namespace Spotify.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260828091636_AddRevokedTokens")]
    partial class AddRevokedTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.AudioContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AudioItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("GenreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ImageItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsForAdult")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AudioItemId");

                    b.HasIndex("GenreId");

                    b.HasIndex("ImageItemId");

                    b.ToTable("AudioContent");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AudioContent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.AudioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BitrateKbps")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalContentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDownloadAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ExternalContentId")
                        .IsUnique()
                        .HasFilter("[ExternalContentId] IS NOT NULL");

                    b.ToTable("AudioItems");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.AuthorContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("AuthorContents");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.AuthorContentAuthor", b =>
                {
                    b.Property<Guid>("AuthorContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorContentId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("AuthorContentId", "AuthorId")
                        .IsUnique();

                    b.ToTable("AuthorContentAuthors");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.AuthorSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ApplicationUserId", "AuthorId")
                        .IsUnique();

                    b.ToTable("AuthorSubscriptions", (string)null);
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.CoverImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoverImages");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Genre", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.ImageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageItems");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.LastPlayed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PositionSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorContentId");

                    b.HasIndex("ApplicationUserId", "AuthorContentId")
                        .IsUnique();

                    b.ToTable("LastPlayedEntries");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.ListeningHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("ListenedSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorContentId");

                    b.HasIndex("ApplicationUserId", "PlayedAt");

                    b.ToTable("ListeningHistory", (string)null);
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Mood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MoodImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MoodImageId");

                    b.ToTable("Moods");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.PlaylistTrack", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("PlaylistId", "TrackId");

                    b.HasIndex("TrackId");

                    b.HasIndex("PlaylistId", "Position")
                        .IsUnique();

                    b.ToTable("PlaylistTracks");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Plugin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plugins");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Podcast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Podcasts");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.TrackTag", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TrackId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TrackTags");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Location.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1111111a-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1084aaa8-e8c0-42eb-8153-4e0d79955220"),
                            Name = "New York"
                        },
                        new
                        {
                            Id = new Guid("1111111b-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1084aaa8-e8c0-42eb-8153-4e0d79955220"),
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("1111111c-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1084aaa8-e8c0-42eb-8153-4e0d79955220"),
                            Name = "Chicago"
                        },
                        new
                        {
                            Id = new Guid("1111111d-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1084aaa8-e8c0-42eb-8153-4e0d79955220"),
                            Name = "Houston"
                        },
                        new
                        {
                            Id = new Guid("2222222a-2222-2222-2222-222222222222"),
                            CountryId = new Guid("2084aaa8-e8c0-42eb-8153-4e0d79955221"),
                            Name = "Beijing"
                        },
                        new
                        {
                            Id = new Guid("2222222b-2222-2222-2222-222222222222"),
                            CountryId = new Guid("2084aaa8-e8c0-42eb-8153-4e0d79955221"),
                            Name = "Shanghai"
                        },
                        new
                        {
                            Id = new Guid("2222222c-2222-2222-2222-222222222222"),
                            CountryId = new Guid("2084aaa8-e8c0-42eb-8153-4e0d79955221"),
                            Name = "Guangzhou"
                        },
                        new
                        {
                            Id = new Guid("2222222d-2222-2222-2222-222222222222"),
                            CountryId = new Guid("2084aaa8-e8c0-42eb-8153-4e0d79955221"),
                            Name = "Shenzhen"
                        },
                        new
                        {
                            Id = new Guid("3333333a-3333-3333-3333-333333333333"),
                            CountryId = new Guid("3084aaa8-e8c0-42eb-8153-4e0d79955222"),
                            Name = "Mumbai"
                        },
                        new
                        {
                            Id = new Guid("3333333b-3333-3333-3333-333333333333"),
                            CountryId = new Guid("3084aaa8-e8c0-42eb-8153-4e0d79955222"),
                            Name = "Delhi"
                        },
                        new
                        {
                            Id = new Guid("3333333c-3333-3333-3333-333333333333"),
                            CountryId = new Guid("3084aaa8-e8c0-42eb-8153-4e0d79955222"),
                            Name = "Bangalore"
                        },
                        new
                        {
                            Id = new Guid("3333333d-3333-3333-3333-333333333333"),
                            CountryId = new Guid("3084aaa8-e8c0-42eb-8153-4e0d79955222"),
                            Name = "Hyderabad"
                        },
                        new
                        {
                            Id = new Guid("4444444a-4444-4444-4444-444444444444"),
                            CountryId = new Guid("4084aaa8-e8c0-42eb-8153-4e0d79955223"),
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = new Guid("4444444b-4444-4444-4444-444444444444"),
                            CountryId = new Guid("4084aaa8-e8c0-42eb-8153-4e0d79955223"),
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("4444444c-4444-4444-4444-444444444444"),
                            CountryId = new Guid("4084aaa8-e8c0-42eb-8153-4e0d79955223"),
                            Name = "Brasília"
                        },
                        new
                        {
                            Id = new Guid("4444444d-4444-4444-4444-444444444444"),
                            CountryId = new Guid("4084aaa8-e8c0-42eb-8153-4e0d79955223"),
                            Name = "Salvador"
                        },
                        new
                        {
                            Id = new Guid("5555555a-5555-5555-5555-555555555555"),
                            CountryId = new Guid("5084aaa8-e8c0-42eb-8153-4e0d79955224"),
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = new Guid("5555555b-5555-5555-5555-555555555555"),
                            CountryId = new Guid("5084aaa8-e8c0-42eb-8153-4e0d79955224"),
                            Name = "Munich"
                        },
                        new
                        {
                            Id = new Guid("5555555c-5555-5555-5555-555555555555"),
                            CountryId = new Guid("5084aaa8-e8c0-42eb-8153-4e0d79955224"),
                            Name = "Hamburg"
                        },
                        new
                        {
                            Id = new Guid("5555555d-5555-5555-5555-555555555555"),
                            CountryId = new Guid("5084aaa8-e8c0-42eb-8153-4e0d79955224"),
                            Name = "Frankfurt"
                        },
                        new
                        {
                            Id = new Guid("6666666a-6666-6666-6666-666666666666"),
                            CountryId = new Guid("6084aaa8-e8c0-42eb-8153-4e0d79955225"),
                            Name = "London"
                        },
                        new
                        {
                            Id = new Guid("6666666b-6666-6666-6666-666666666666"),
                            CountryId = new Guid("6084aaa8-e8c0-42eb-8153-4e0d79955225"),
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = new Guid("6666666c-6666-6666-6666-666666666666"),
                            CountryId = new Guid("6084aaa8-e8c0-42eb-8153-4e0d79955225"),
                            Name = "Birmingham"
                        },
                        new
                        {
                            Id = new Guid("6666666d-6666-6666-6666-666666666666"),
                            CountryId = new Guid("6084aaa8-e8c0-42eb-8153-4e0d79955225"),
                            Name = "Leeds"
                        },
                        new
                        {
                            Id = new Guid("7777777a-7777-7777-7777-777777777777"),
                            CountryId = new Guid("7084aaa8-e8c0-42eb-8153-4e0d79955226"),
                            Name = "Paris"
                        },
                        new
                        {
                            Id = new Guid("7777777b-7777-7777-7777-777777777777"),
                            CountryId = new Guid("7084aaa8-e8c0-42eb-8153-4e0d79955226"),
                            Name = "Lyon"
                        },
                        new
                        {
                            Id = new Guid("7777777c-7777-7777-7777-777777777777"),
                            CountryId = new Guid("7084aaa8-e8c0-42eb-8153-4e0d79955226"),
                            Name = "Marseille"
                        },
                        new
                        {
                            Id = new Guid("7777777d-7777-7777-7777-777777777777"),
                            CountryId = new Guid("7084aaa8-e8c0-42eb-8153-4e0d79955226"),
                            Name = "Toulouse"
                        },
                        new
                        {
                            Id = new Guid("8888888a-8888-8888-8888-888888888888"),
                            CountryId = new Guid("8084aaa8-e8c0-42eb-8153-4e0d79955227"),
                            Name = "Rome"
                        },
                        new
                        {
                            Id = new Guid("8888888b-8888-8888-8888-888888888888"),
                            CountryId = new Guid("8084aaa8-e8c0-42eb-8153-4e0d79955227"),
                            Name = "Milan"
                        },
                        new
                        {
                            Id = new Guid("8888888c-8888-8888-8888-888888888888"),
                            CountryId = new Guid("8084aaa8-e8c0-42eb-8153-4e0d79955227"),
                            Name = "Naples"
                        },
                        new
                        {
                            Id = new Guid("8888888d-8888-8888-8888-888888888888"),
                            CountryId = new Guid("8084aaa8-e8c0-42eb-8153-4e0d79955227"),
                            Name = "Florence"
                        },
                        new
                        {
                            Id = new Guid("9999999a-9999-9999-9999-999999999999"),
                            CountryId = new Guid("9084aaa8-e8c0-42eb-8153-4e0d79955228"),
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = new Guid("9999999b-9999-9999-9999-999999999999"),
                            CountryId = new Guid("9084aaa8-e8c0-42eb-8153-4e0d79955228"),
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = new Guid("9999999c-9999-9999-9999-999999999999"),
                            CountryId = new Guid("9084aaa8-e8c0-42eb-8153-4e0d79955228"),
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = new Guid("9999999d-9999-9999-9999-999999999999"),
                            CountryId = new Guid("9084aaa8-e8c0-42eb-8153-4e0d79955228"),
                            Name = "Seville"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CountryId = new Guid("a084aaa8-e8c0-42eb-8153-4e0d79955229"),
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaab-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CountryId = new Guid("a084aaa8-e8c0-42eb-8153-4e0d79955229"),
                            Name = "Vancouver"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaac-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CountryId = new Guid("a084aaa8-e8c0-42eb-8153-4e0d79955229"),
                            Name = "Montreal"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaad-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CountryId = new Guid("a084aaa8-e8c0-42eb-8153-4e0d79955229"),
                            Name = "Calgary"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbba-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CountryId = new Guid("b084aaa8-e8c0-42eb-8153-4e0d7995522a"),
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CountryId = new Guid("b084aaa8-e8c0-42eb-8153-4e0d7995522a"),
                            Name = "Melbourne"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbb1-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CountryId = new Guid("b084aaa8-e8c0-42eb-8153-4e0d7995522a"),
                            Name = "Brisbane"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbb2-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CountryId = new Guid("b084aaa8-e8c0-42eb-8153-4e0d7995522a"),
                            Name = "Perth"
                        },
                        new
                        {
                            Id = new Guid("ccccccca-cccc-cccc-cccc-cccccccccccc"),
                            CountryId = new Guid("c084aaa8-e8c0-42eb-8153-4e0d7995522b"),
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = new Guid("cccccccb-cccc-cccc-cccc-cccccccccccc"),
                            CountryId = new Guid("c084aaa8-e8c0-42eb-8153-4e0d7995522b"),
                            Name = "Osaka"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CountryId = new Guid("c084aaa8-e8c0-42eb-8153-4e0d7995522b"),
                            Name = "Kyoto"
                        },
                        new
                        {
                            Id = new Guid("ccccccc1-cccc-cccc-cccc-cccccccccccc"),
                            CountryId = new Guid("c084aaa8-e8c0-42eb-8153-4e0d7995522b"),
                            Name = "Yokohama"
                        },
                        new
                        {
                            Id = new Guid("ddddddda-dddd-dddd-dddd-dddddddddddd"),
                            CountryId = new Guid("d084aaa8-e8c0-42eb-8153-4e0d7995522c"),
                            Name = "Seoul"
                        },
                        new
                        {
                            Id = new Guid("dddddddb-dddd-dddd-dddd-dddddddddddd"),
                            CountryId = new Guid("d084aaa8-e8c0-42eb-8153-4e0d7995522c"),
                            Name = "Busan"
                        },
                        new
                        {
                            Id = new Guid("dddddddc-dddd-dddd-dddd-dddddddddddd"),
                            CountryId = new Guid("d084aaa8-e8c0-42eb-8153-4e0d7995522c"),
                            Name = "Incheon"
                        },
                        new
                        {
                            Id = new Guid("ddddddd1-dddd-dddd-dddd-dddddddddddd"),
                            CountryId = new Guid("d084aaa8-e8c0-42eb-8153-4e0d7995522c"),
                            Name = "Daegu"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-0000-0000-0000-000000000001"),
                            CountryId = new Guid("f084aaa8-e8c0-42eb-8153-4e0d7995522e"),
                            Name = "Mexico City"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-0000-0000-0000-000000000002"),
                            CountryId = new Guid("f084aaa8-e8c0-42eb-8153-4e0d7995522e"),
                            Name = "Guadalajara"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-0000-0000-0000-000000000003"),
                            CountryId = new Guid("f084aaa8-e8c0-42eb-8153-4e0d7995522e"),
                            Name = "Monterrey"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-0000-0000-0000-000000000004"),
                            CountryId = new Guid("f084aaa8-e8c0-42eb-8153-4e0d7995522e"),
                            Name = "Cancún"
                        },
                        new
                        {
                            Id = new Guid("1111111e-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1184aaa8-e8c0-42eb-8153-4e0d7995522f"),
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = new Guid("1111111f-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1184aaa8-e8c0-42eb-8153-4e0d7995522f"),
                            Name = "Rotterdam"
                        },
                        new
                        {
                            Id = new Guid("1211111e-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1284aaa8-e8c0-42eb-8153-4e0d79955230"),
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = new Guid("1211111f-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1284aaa8-e8c0-42eb-8153-4e0d79955230"),
                            Name = "Córdoba"
                        },
                        new
                        {
                            Id = new Guid("1311111e-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1384aaa8-e8c0-42eb-8153-4e0d79955231"),
                            Name = "Stockholm"
                        },
                        new
                        {
                            Id = new Guid("1311111f-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1384aaa8-e8c0-42eb-8153-4e0d79955231"),
                            Name = "Gothenburg"
                        },
                        new
                        {
                            Id = new Guid("1411111e-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1484aaa8-e8c0-42eb-8153-4e0d79955232"),
                            Name = "Zurich"
                        },
                        new
                        {
                            Id = new Guid("1411111f-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1484aaa8-e8c0-42eb-8153-4e0d79955232"),
                            Name = "Geneva"
                        },
                        new
                        {
                            Id = new Guid("1511111e-1111-1111-1111-111111111111"),
                            CountryId = new Guid("1584aaa8-e8c0-42eb-8153-4e0d79955233"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("5758bf18-11e6-44a6-ae60-1d8ab273eb49"),
                            CountryId = new Guid("1584aaa8-e8c0-42eb-8153-4e0d79955233"),
                            Name = "Marina Bay"
                        });
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Location.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1084aaa8-e8c0-42eb-8153-4e0d79955220"),
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("2084aaa8-e8c0-42eb-8153-4e0d79955221"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("3084aaa8-e8c0-42eb-8153-4e0d79955222"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("4084aaa8-e8c0-42eb-8153-4e0d79955223"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("5084aaa8-e8c0-42eb-8153-4e0d79955224"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("6084aaa8-e8c0-42eb-8153-4e0d79955225"),
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("7084aaa8-e8c0-42eb-8153-4e0d79955226"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("8084aaa8-e8c0-42eb-8153-4e0d79955227"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("9084aaa8-e8c0-42eb-8153-4e0d79955228"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("a084aaa8-e8c0-42eb-8153-4e0d79955229"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("b084aaa8-e8c0-42eb-8153-4e0d7995522a"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("c084aaa8-e8c0-42eb-8153-4e0d7995522b"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("d084aaa8-e8c0-42eb-8153-4e0d7995522c"),
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("f084aaa8-e8c0-42eb-8153-4e0d7995522e"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("1184aaa8-e8c0-42eb-8153-4e0d7995522f"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("1284aaa8-e8c0-42eb-8153-4e0d79955230"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("1384aaa8-e8c0-42eb-8153-4e0d79955231"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("1484aaa8-e8c0-42eb-8153-4e0d79955232"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("1584aaa8-e8c0-42eb-8153-4e0d79955233"),
                            Name = "Singapore"
                        });
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Security.RevokedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAuthor")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SettingsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SettingsId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("ApplicationUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "66666666-6666-6666-6666-666666666666",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            IsAuthor = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PhoneNumberConfirmed = false,
                            SettingsId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            SubscriptionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivationKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorContentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("AuthorContentId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Language = 2
                        });
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(13,2)");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Default subscription",
                            Name = "Default",
                            Price = 0m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Premium subscription",
                            Name = "Premium",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Student subscription",
                            Name = "Student",
                            Price = 4.99m
                        });
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAdult")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Birthdate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CityId = new Guid("5758bf18-11e6-44a6-ae60-1d8ab273eb49"),
                            CountryId = new Guid("1084aaa8-e8c0-42eb-8153-4e0d79955220"),
                            IsAdult = true,
                            RegisteredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRead")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CanCreate = true,
                            CanDelete = false,
                            CanRead = true,
                            CanUpdate = false,
                            ConcurrencyStamp = "11111111-1111-1111-1111-111111111111",
                            Description = "Default role for self-registered users",
                            Name = "Self-Registered",
                            NormalizedName = "SELF-REGISTERED"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true,
                            ConcurrencyStamp = "22222222-2222-2222-2222-222222222222",
                            Description = "Administrator role with full permissions",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Episode", b =>
                {
                    b.HasBaseType("Spotify.Domain.Entities.Content.AudioContent");

                    b.Property<Guid>("PodcastId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("PodcastId");

                    b.HasDiscriminator().HasValue("Episode");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Album", b =>
                {
                    b.HasBaseType("Spotify.Domain.Entities.Content.AudioContent");

                    b.Property<Guid>("CoverImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.HasIndex("CoverImageId");

                    b.HasDiscriminator().HasValue("Album");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Audiobook", b =>
                {
                    b.HasBaseType("Spotify.Domain.Entities.Content.AudioContent");

                    b.Property<Guid>("AuthorContentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("AuthorContentId");

                    b.HasDiscriminator().HasValue("Audiobook");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Track", b =>
                {
                    b.HasBaseType("Spotify.Domain.Entities.Content.AudioContent");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdult")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PlaysNumber")
                        .HasColumnType("bigint");

                    b.HasIndex("AlbumId");

                    b.HasIndex("MoodId");

                    b.ToTable("AudioContent", t =>
                        {
                            t.Property("IsDraft")
                                .HasColumnName("Track_IsDraft");
                        });

                    b.HasDiscriminator().HasValue("Track");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.User.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.User.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.AudioContent", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Content.AudioItem", "AudioItem")
                        .WithMany()
                        .HasForeignKey("AudioItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Spotify.Domain.Entities.Content.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Spotify.Domain.Entities.Content.ImageItem", "ImageItem")
                        .WithMany()
                        .HasForeignKey("ImageItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AudioItem");

                    b.Navigation("Genre");

                    b.Navigation("ImageItem");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.AuthorContent", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Content.AudioContent", "Item")
                        .WithMany("Authors")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.AuthorContentAuthor", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Content.AuthorContent", "AuthorContent")
                        .WithMany("Authors")
                        .HasForeignKey("AuthorContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", "Author")
                        .WithMany("AuthoredContent")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("AuthorContent");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.AuthorSubscription", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", "ApplicationUser")
                        .WithMany("AuthorSubscriptions")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", "Author")
                        .WithMany("Followers")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.LastPlayed", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spotify.Domain.Entities.Content.AuthorContent", "AuthorContent")
                        .WithMany()
                        .HasForeignKey("AuthorContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("AuthorContent");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.ListeningHistory", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", "ApplicationUser")
                        .WithMany("ListeningHistory")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spotify.Domain.Entities.Content.AuthorContent", "AuthorContent")
                        .WithMany()
                        .HasForeignKey("AuthorContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("AuthorContent");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Mood", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Content.ImageItem", "MoodImage")
                        .WithMany()
                        .HasForeignKey("MoodImageId");

                    b.Navigation("MoodImage");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Playlist", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", "ApplicationUser")
                        .WithMany("Playlists")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.PlaylistTrack", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Content.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spotify.Domain.Entities.Content.Track", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.TrackTag", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Content.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spotify.Domain.Entities.Content.Track", "Track")
                        .WithMany("TrackTags")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Location.City", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Location.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.ApplicationUser", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.User.Settings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spotify.Domain.Entities.User.Subscription", "Subscription")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.Like", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", "ApplicationUser")
                        .WithMany("Likes")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spotify.Domain.Entities.Content.AuthorContent", "AuthorContent")
                        .WithMany()
                        .HasForeignKey("AuthorContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("AuthorContent");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.UserProfile", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Location.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spotify.Domain.Entities.Location.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spotify.Domain.Entities.User.ApplicationUser", "ApplicationUser")
                        .WithOne("Profile")
                        .HasForeignKey("Spotify.Domain.Entities.User.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Episode", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Content.Podcast", "Podcast")
                        .WithMany("Episodes")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Podcast");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Album", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Content.CoverImage", "CoverImage")
                        .WithMany("Albums")
                        .HasForeignKey("CoverImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoverImage");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Audiobook", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Content.AuthorContent", "AuthorContent")
                        .WithMany()
                        .HasForeignKey("AuthorContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorContent");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Track", b =>
                {
                    b.HasOne("Spotify.Domain.Entities.Content.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Spotify.Domain.Entities.Content.Mood", "Mood")
                        .WithMany()
                        .HasForeignKey("MoodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Album");

                    b.Navigation("Mood");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.AudioContent", b =>
                {
                    b.Navigation("Authors");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.AuthorContent", b =>
                {
                    b.Navigation("Authors");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.CoverImage", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Playlist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Podcast", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Location.City", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Location.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.ApplicationUser", b =>
                {
                    b.Navigation("AuthorSubscriptions");

                    b.Navigation("AuthoredContent");

                    b.Navigation("Followers");

                    b.Navigation("Likes");

                    b.Navigation("ListeningHistory");

                    b.Navigation("Playlists");

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Spotify.Domain.Entities.User.Subscription", b =>
                {
                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Spotify.Domain.Entities.Content.Track", b =>
                {
                    b.Navigation("PlaylistTracks");

                    b.Navigation("TrackTags");
                });
#pragma warning restore 612, 618
        }
    }
}
